services:
  scraperr:
    depends_on:
      - scraperr_api
    image: jpyles0524/scraperr:latest
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: scraperr
    command: ["npm", "run", "start"]
    environment:
      - NEXT_PUBLIC_API_URL=https://scraperrapi.mediacomvalentin.de # your API URL
      - SERVER_URL=https://scraperrapi.mediacomvalentin.de # your docker container API URL
    ports:
      - 3777:3777
    networks:
      - web
  scraperr_api:
    init: True
    image: jpyles0524/scraperr_api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - LOG_LEVEL=INFO
      - SECRET_KEY=your_secret_key # used to encode authentication tokens (can be a random string)
      - ALGORITHM=HS256 # authentication encoding algorithm
      - ACCESS_TOKEN_EXPIRE_MINUTES=600 # access token expire minutes
    container_name: scraperr_api
    ports:
      - 8000:8000
    volumes:
      - "$PWD/data:/project/data"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
networks:
  web:
